### ISSUE TITLE
`h5filepath` versus `filename`

### ISSUE THREAD

**Issue by xiangzhu** [CreRecombinase/EigenH5#1]
@CreRecombinase  I think this is only a minor issue, but can be useful if different functions use the same variable name to indicate the data file.

```r
> trait_mat <- EigenH5::read_matrix_h5(filename=pheno_file, groupname="trait", dataname="ymat")
> trait_df <- EigenH5::read_df_h5(filename=pheno_file, groupname="SimulationInfo")
Error in EigenH5::read_df_h5(filename = pheno_file, groupname = "SimulationInfo") :
  unused argument (filename = pheno_file)
> trait_df <- EigenH5::read_df_h5(h5filepath=pheno_file, groupname="SimulationInfo")
```

However, it seems that you have already made this change. Related lines in `utils.R`:

- https://github.com/CreRecombinase/EigenH5/blob/75c5364e42865efe032af080094602d1fcb8362b/R/utils.R#L5
- https://github.com/CreRecombinase/EigenH5/blob/75c5364e42865efe032af080094602d1fcb8362b/R/utils.R#L151 

Should I re-install the package?

**Comment by CreRecombinase** [comment]
Thanks for the feedback! I've switched over to only using `filename` to refer to files.  I'd say hold out on re-installing (I'm about to come out with a new release)
